const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const wedding=new Date('2026-08-08T11:00:00+09:00');function tick(){const d=wedding-new Date();$('#dday').textContent=d>0?'D-'+Math.ceil(d/86400000):'Wedding Day'}tick();setInterval(tick,60000);const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.15});$$('.reveal').forEach(el=>io.observe(el));window.addEventListener('scroll',()=>{$('#progress').style.width=(scrollY/(document.body.scrollHeight-innerHeight)*100)+'%'});function petal(){const p=document.createElement('span');p.className='petal';p.textContent=Math.random()>.5?'❀':'✦';p.style.left=Math.random()*100+'vw';p.style.fontSize=10+Math.random()*16+'px';p.style.opacity=.45+Math.random()*.45;p.style.setProperty('--x',(Math.random()*160-80)+'px');p.style.animationDuration=5+Math.random()*6+'s';$('#petals').appendChild(p);setTimeout(()=>p.remove(),11000)}setInterval(petal,420);$$('.acc-item>button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}$$('.copy').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast('계좌번호가 복사되었습니다')}catch(e){toast(b.dataset.copy)}});$$('.gallery-grid img').forEach(img=>img.onclick=()=>{const lb=$('#lightbox');lb.querySelector('img').src=img.src;lb.classList.add('show')});$('#lightbox button').onclick=()=>$('#lightbox').classList.remove('show');$('#lightbox').onclick=e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('show')};$('#shareBtn').onclick=async()=>{const data={title:'HEEHO ♥ HAEUN Wedding Invitation',text:'이희호 ♥ 강하은 결혼식에 초대합니다.',url:location.href};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('URL이 복사되었습니다')}};$('#urlBtn').onclick=async()=>{await navigator.clipboard.writeText(location.href);toast('URL이 복사되었습니다')};let ac,osc,gain,playing=false;$('#musicBtn').onclick=()=>{if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();gain=ac.createGain();gain.gain.value=.025;gain.connect(ac.destination);osc=ac.createOscillator();osc.type='sine';osc.frequency.value=523.25;osc.connect(gain);osc.start()}playing=!playing;gain.gain.setTargetAtTime(playing?.025:0,ac.currentTime,.1);$('#musicBtn').textContent=playing?'Ⅱ':'♪'};

// v12: T맵 앱이 없거나 인앱 브라우저에서 막혀도 주소를 복사하고 웹 검색으로 안내
const tmapBtn=document.querySelector('#tmapBtn');
if(tmapBtn){
  tmapBtn.addEventListener('click',()=>{
    const address='경기도 남양주시 다산순환로 20 파로스컨벤션';
    const keyword=encodeURIComponent('파로스컨벤션 다산순환로20');
    try{ navigator.clipboard && navigator.clipboard.writeText(address); }catch(e){}
    toast('주소를 복사했습니다. 티맵에서 붙여넣어 검색하세요.');
    setTimeout(()=>{ window.open('https://www.google.com/search?q='+keyword+'+%ED%8B%B0%EB%A7%B5','_blank','noopener'); },700);
  });
}
